name: detox-e2e-test
on: [push]
jobs:
    run-detox-e2e-test:
        runs-on: self-hosted
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - run: dir
            - run: cd frontend
            - run: yarn install
            - run: npx detox build -c android.emu.release
            - run: npx detox test -c android.emu.release
