name: detox-e2e-test
on:
    push:
        branches:
            - dev-nik/feature/deploy-to-android
jobs:
    run-detox-e2e-test:
        runs-on: self-hosted
        steps:
            - name: Check out repository
              working-directory: ./Frontend
              uses: actions/checkout@v3
            - name: Install dependencies
              uses: actions/setup-node@v3
              run: yarn install
              with:
                  node-version: "18.15"
            - name: Install items
              run: |
                  pwd
                  npx detox build -c android.emu.release
                  npx detox test -c android.emu.release
